import { chromium } from 'playwright';
import { build } from 'esbuild';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createServer } from 'node:http';

const evidence = path.resolve('.evidence/checkpoint');
await mkdir(evidence, { recursive: true });
const profile = await mkdtemp(path.join(os.tmpdir(), 'carry-checkpoint-'));
const extensionPath = path.resolve('extension');
const executablePath = process.env.CHROME_PATH || chromium.executablePath();
const report = { startedAt: new Date().toISOString(), profile, checks: [], errors: [], workerRequests: [] };
function pass(name, detail) { report.checks.push({ name, detail }); console.log('PASS', name); }
async function eventually(fn, timeout = 12000) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) { if (await fn()) return; await new Promise(r => setTimeout(r, 75)); }
  throw new Error('Timed out waiting for observed browser state.');
}
let context;
const readme = await readFile('README.md', 'utf8');
const escaped = readme.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const server = createServer((req,res) => { res.setHeader('Content-Type','text/html'); res.end(`<!doctype html><html><head><title>Hackathon build brief</title></head><body><h1>Hackathon build brief</h1><p id="selection">Keep this browser context with the note.</p><pre>${escaped}</pre><p hidden>HIDDEN_TEXT_NEGATIVE_CONTROL</p><a href="/next">Next page</a></body></html>`); });
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
const launch = () => chromium.launchPersistentContext(profile, { executablePath, headless: true, viewport: { width: 430, height: 1000 }, ignoreDefaultArgs: ['--disable-extensions'], args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`] });
async function keyboard(page, key, nativeCode, windowsCode) {
  const session = await context.newCDPSession(page);
  for (const type of ['rawKeyDown', 'keyUp']) await session.send('Input.dispatchKeyEvent', { type, modifiers: 12, key, code: `Key${key}`, windowsVirtualKeyCode: windowsCode, nativeVirtualKeyCode: nativeCode, isSystemKey: true });
  await session.detach();
}
try {
  context = await launch();
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  const id = new URL(worker.url()).host;
  report.extensionId = id; report.chrome = context.browser().version();
  context.on('request', request => { if (request.serviceWorker()) report.workerRequests.push({ url: request.url(), method: request.method() }); });
  context.on('weberror', error => report.errors.push(error.error().message));
  const panel = context.pages()[0];
  await panel.goto(`chrome-extension://${id}/panel.html`);
  await panel.getByText('Local workspace ready.', { exact: true }).waitFor();
  const state = () => panel.evaluate(async () => { const r = await chrome.runtime.sendMessage({type:'state'}); if (!r.ok) throw new Error(r.error); return r.value; });
  const message = (type, values = {}) => panel.evaluate(async ({type,values}) => chrome.runtime.sendMessage({type,...values}), { type, values });
  assert.equal((await state()).contexts.length, 0);
  assert((await worker.evaluate(() => chrome.commands.getAll())).some(c => c.name === 'capture-context' && c.shortcut));
  pass('Unpacked MV3 loads with registered capture command', { id, chrome: report.chrome });
  const page = await context.newPage(); await page.goto(origin);
  await page.locator('#selection').evaluate(el => { const range = document.createRange(); range.selectNodeContents(el); window.getSelection().removeAllRanges(); window.getSelection().addRange(range); });
  const beforeTabs = await worker.evaluate(() => chrome.tabs.query({ active: true }));
  const beforeNotifications = await worker.evaluate(() => chrome.notifications.getAll());
  const pageCount = context.pages().length;
  await page.keyboard.press('Meta+Shift+y');
  await new Promise(r=>setTimeout(r,200));
  assert.equal((await state()).contexts.length,0);
  pass('Ordinary page keyboard input is a negative control for browser command routing');
  await keyboard(page, 'Y', 16, 89);
  await eventually(async () => (await state()).contexts.length === 1);
  const snapshot = (await state()).contexts[0];
  assert.equal(snapshot.url, `${origin}/`); assert.equal(snapshot.title, 'Hackathon build brief');
  assert.equal(snapshot.selection, 'Keep this browser context with the note.');
  assert(snapshot.visibleText.includes('hackathon')); assert(!snapshot.visibleText.includes('HIDDEN_TEXT_NEGATIVE_CONTROL'));
  assert.equal(snapshot.availability, 'available'); assert.equal(snapshot.source, 'hotkey');
  assert.equal(context.pages().length, pageCount);
  assert.deepEqual(await worker.evaluate(() => chrome.notifications.getAll()), beforeNotifications);
  assert.deepEqual((await worker.evaluate(() => chrome.tabs.query({ active: true }))).map(t=>t.id), beforeTabs.map(t=>t.id));
  pass('Real hotkey captures original page, selection, visible text, and time without focus or notification');
  await page.goto(`${origin}/changed-after-capture`);
  await panel.bringToFront();
  await panel.locator('#note').fill('Keep this option for our project meeting.');
  await panel.getByRole('button', {name:'Save note locally', exact:true}).click();
  await eventually(async () => (await state()).notes.length === 1);
  const note = (await state()).notes[0];
  assert.equal(note.contextId, snapshot.id); assert.equal(note.source, 'manual');
  assert.equal(note.reasoning,'unavailable');
  await panel.reload(); await panel.getByText('Local workspace ready.', {exact:true}).waitFor();
  assert.equal((await state()).notes[0].id,note.id);
  assert.equal((await state()).contexts[0].url,`${origin}/`);
  await panel.screenshot({ path: path.join(evidence,'notes-persisted.png'),fullPage:true });
  pass('Manual note remains paired to pre-tab-change context and persists after reload');
  await panel.getByRole('button',{name:'Review',exact:true}).click();
  await panel.locator('#task-title').fill('Return to the saved option');
  await panel.locator('#next-step').fill('Compare the option with the meeting requirements.');
  await panel.getByRole('button',{name:'Create local draft',exact:true}).click();
  await eventually(async () => (await state()).tasks.length===1);
  const task = (await state()).tasks[0];
  assert.equal(task.authority,'proposal-only'); assert.equal(task.delivery,'queued-decision');
  await panel.goto(`chrome-extension://${id}/panel.html#context=${snapshot.id}`);
  await panel.getByText('Draft only. Opening this link runs no task.',{exact:true}).waitFor();
  assert.equal((await state()).tasks[0].revision,1); assert.equal((await state()).outbox.length,0);
  pass('Resume restores local context and next step with no task execution');
  await panel.goto(`chrome-extension://${id}/panel.html#context=missing-context`);
  await panel.getByText('This context is not stored in this browser. Local links do not transfer records between devices.',{exact:true}).waitFor();
  assert(await panel.getByRole('button',{name:'Save note locally',exact:true}).isDisabled());
  pass('Missing local resume ID is explicit and cannot attach to another context');
  await panel.goto(`chrome-extension://${id}/panel.html`);
  await panel.getByText('Local workspace ready.',{exact:true}).waitFor();
  await panel.getByRole('button',{name:'Meeting',exact:true}).click();
  const dateValue = time => { const date = new Date(time); return new Date(time-date.getTimezoneOffset()*60000).toISOString().slice(0,19); };
  await panel.locator('#meeting-title').fill('Checkpoint reminder');
  await panel.locator('#join-url').fill(`${origin}/join`);
  await panel.locator('#starts-at').fill(dateValue(Date.now()+180000));
  await panel.locator('#remind-at').fill(dateValue(Date.now()+5000));
  await panel.getByRole('button',{name:'Save reminder',exact:true}).click();
  await eventually(async ()=>(await state()).meetings.length===1);
  let meeting=(await state()).meetings[0];
  assert(await worker.evaluate(async id => !!await chrome.alarms.get(`meeting:${id}`), meeting.id));
  await eventually(async()=>!!(await state()).meetings[0].reminderFiredAt);
  meeting=(await state()).meetings[0];
  assert(meeting.reminderFiredAt>=meeting.remindAt);
  await eventually(async()=>!!(await worker.evaluate(()=>chrome.notifications.getAll()))[`meeting:${meeting.id}`]);
  const notifications=await worker.evaluate(()=>chrome.notifications.getAll());
  assert(notifications[`meeting:${meeting.id}`]);
  pass('Saved meeting time triggers a real chrome.alarms notification', { remindAt:meeting.remindAt,firedAt:meeting.reminderFiredAt });
  assert(await panel.getByRole('button',{name:'Open meeting audio',exact:true}).isEnabled());
  assert(await panel.getByRole('button',{name:'Takeover unavailable',exact:true}).isDisabled());
  const takeover=await message('meeting-action',{id:meeting.id,action:'takeover'});
  assert.equal(takeover.ok,false); assert.match(takeover.error,/unavailable/);
  assert.equal((await state()).meetings[0].status,'scheduled');
  const opened=context.waitForEvent('page');
  await panel.getByRole('button',{name:'Join',exact:true}).click();
  const joined=await opened; await joined.waitForURL(`${origin}/join`);
  await panel.bringToFront();
  await panel.getByRole('button',{name:'Mark away',exact:true}).click();
  await eventually(async()=>(await state()).meetings[0].status==='away');
  await panel.getByRole('button',{name:'Return',exact:true}).click();
  await eventually(async()=>!!(await state()).absences[0].endAt);
  assert.equal((await state()).meetings[0].captureStatus,'unavailable');
  await panel.getByRole('button',{name:'End meeting',exact:true}).click();
  await eventually(async()=>(await state()).meetings[0].status==='ended');
  await panel.getByText('No transcript captured. What you missed and action-item summaries are unavailable.',{exact:true}).waitFor();
  await panel.screenshot({path:path.join(evidence,'meeting-ended.png'),fullPage:true});
  pass('Meeting join URL, absence boundaries, return/end persist; unavailable speech cannot fake Takeover');
  await panel.getByRole('button',{name:'Settings',exact:true}).click();
  await panel.locator('#sync-mode').selectOption('sync');
  await eventually(async()=>(await state()).settings.syncMode==='sync');
  assert.equal((await state()).outbox.length,0); assert.equal((await state()).notes[0].syncEligible,false);
  await panel.locator('#sync-mode').selectOption('local');
  await eventually(async()=>(await state()).settings.syncMode==='local');
  const approve=await message('approve-sync',{noteIds:[note.id],taskIds:[task.id]});
  assert.equal(approve.ok,false);
  await message('send-approved');
  await worker.evaluate(()=>fetch(chrome.runtime.getURL('manifest.json')).then(r=>r.json()));
  await eventually(()=>report.workerRequests.some(r=>r.url.endsWith('/manifest.json')));
  assert.equal(report.workerRequests.filter(r=>/^https?:/.test(r.url)).length,0);
  pass('Local mode has zero observed worker HTTP requests, with positive network instrumentation control');
  pass('Enabling sync does not enqueue private history; local mode denies batch approval');
  await panel.screenshot({path:path.join(evidence,'settings-local.png'),fullPage:true});
  await build({entryPoints:['extension/src/db.ts'],outfile:'extension/foundation/proof-db.js',bundle:true,format:'esm',target:'chrome120'});
  const atomic=await panel.evaluate(async()=>{
    const db=await import(chrome.runtime.getURL('foundation/proof-db.js'));
    await db.writeBatch([{store:'settings',value:{id:'proof-atomic',value:'committed'}},{store:'settings',value:{id:'proof-companion',value:'committed'}}]);
    const before=(await db.get('settings','proof-atomic')).value;
    let rejected=false;
    try { await db.writeBatch([{store:'settings',value:{id:'proof-atomic',value:'must-rollback'}},{store:'settings',value:{value:'missing-key'}}]); } catch { rejected=true; }
    return {before,rejected,after:(await db.get('settings','proof-atomic')).value,companion:(await db.get('settings','proof-companion')).value};
  });
  assert.deepEqual(atomic,{before:'committed',rejected:true,after:'committed',companion:'committed'});
  pass('Real IndexedDB multi-write failure rejects and rolls back prior writes');
  // Restricted page is exercised through the same native shortcut path.
  await page.goto('chrome://version/'); await page.bringToFront(); await keyboard(page,'Y',16,89);
  await eventually(async()=>(await state()).contexts.length===2);
  assert.equal((await state()).contexts.find(c=>c.url==='chrome://version/').availability,'restricted');
  pass('Restricted browser page records explicit unavailable page text');
  await context.close();
  context=await launch();
  const restarted=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');
  const panel2=context.pages()[0]; await panel2.goto(`chrome-extension://${new URL(restarted.url()).host}/panel.html`);
  await panel2.getByText('Local workspace ready.',{exact:true}).waitFor();
  const persisted=await panel2.evaluate(()=>chrome.runtime.sendMessage({type:'state'}));
  assert.equal(persisted.value.notes[0].id,note.id); assert.equal(persisted.value.tasks[0].id,task.id);
  assert.equal(persisted.value.meetings[0].status,'ended'); assert(persisted.value.absences[0].endAt);
  pass('Full browser restart retains notes, tasks, meeting state, and absence boundaries');
  assert.deepEqual(report.errors,[]);
  report.result='PASS';
} catch(error) { report.result='FAIL'; report.failure=error.stack; console.error(error); process.exitCode=1; }
finally {
  if(context)await context.close(); server.close();
  report.finishedAt=new Date().toISOString();
  await writeFile(path.join(evidence,'report.json'),JSON.stringify(report,null,2));
  console.log('RESULT:',report.result);
}
